implement incremental backoff for s3 reads
RaRe-Technologies/smart_open pull request #552
Opened 2020-10-25 09:01 UTC by mpenkov

Fix #551 

The previous implementation did a single retry without sleeping.

The proposed approach is to perform multiple retries with incremental backoff (sleep longer after consecutive failures).

2020-10-25 09:47 UTC, piskvorky requested changes
boto3 has its own retry functionality: 
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html

Why not use that?

2020-10-25 09:47 UTC, piskvorky commented on smart_open/s3.py
> +            else:
Why not `break` right below `binary = self._read_from_body(size)?

2020-10-25 09:47 UTC, piskvorky commented on smart_open/s3.py
> +                logger.error(
`logging.warning` more appropriate.

2020-10-25 09:47 UTC, piskvorky commented on smart_open/s3.py
> +                    'caught %r, retrying %d more times',
Let's also log the sleep time for the next attempt.

```suggestion
                    'caught %r, will automatically retry in %.2fs (%d more attempts left)',
```

2021-01-08 06:37 UTC, mpenkov commented
This is ready for another round @piskvorky

2021-01-15 06:49 UTC, merged