Add Python 3.9 to testing
RaRe-Technologies/smart_open pull request #634
Opened 2021-08-03 22:43 UTC by judahrand

#### Motivation

Pretty self explanatory. Should probably test on the newest Python version.

2021-08-04 07:27 UTC, piskvorky requested changes

2021-08-04 07:27 UTC, piskvorky commented on .github/workflows/python-package-win.yml
> +            toxenv: "py38-doctest"
Why py38?

2021-08-04 08:31 UTC, judahrand commented on .github/workflows/python-package-win.yml
> +            toxenv: "py38-doctest"
Whoops! Late night typo.

2021-08-04 08:34 UTC, judahrand commented on .github/workflows/python-package-win.yml
> +            toxenv: "py38-doctest"
Sorted now!

2021-08-04 08:51 UTC, piskvorky commented
Thanks! Let's wait for @mpenkov 's blessing :)

2021-08-18 03:46 UTC, mpenkov reviewed
Looks great! Thank you @judahrand !

2021-08-18 03:46 UTC, merged